name: Create release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  build-workflow:
    uses: ./.github/workflows/build-jobs.yaml
  create-release:
    runs-on: ubuntu-latest
    needs: build-workflow
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        with:
          config: ./configs/cliff.toml
          args: --verbose
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: "./"
      - name: Rename artifacts
        run: |
          for postfix in windows linux macos
          do
            if [[ $postfix == windows ]]
            then
              mv ./hactool-$postfix/hactool* ./hactool-$postfix/hactool-$postfix.exe
            else
              mv ./hactool-$postfix/hactool* ./hactool-$postfix/hactool-$postfix
            fi
          done
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "hactool-*/hactool-*"
          prerelease: false
          name: "hactool-${{ github.ref_name }}"
          bodyFile: "git-cliff/CHANGELOG.md"
